shilltg = '🌜 Samari is launching soon! 🌛\n' \
          'Join the community on TG – you won’t waste your time!\n\n' \
          'TELEGRAM: t.me/SamariFinance\n' \
          'WEBSITE: Samari.finance\n\n'\
            '👉 Team doxed\n' \
            '👉 Active community\n' \
            '👉 Charitable Organization\n' \
            '👉 Marketing Strategy\n' \
            '👉 $100K MC at launch – stable liquidity, no p&d scheme\n' \
            '👉 Solid tokenomics\n\n' \
            '💰 BUY $Samari (V2): link\n' \
            '📈 CHART (V2): link\n' \
            '🔒 LIQUIDITY BURNED // OWNERSHIP RENOUNCED\n' \
            '✅ VERIFIED CONTRACT: link\n'

shillreddit = ''

commands = {
    "start": 'Heya, I\'m your local Samaritan ❤️ Available commands:\n'
             '\nGeneral:\n'
             '/commands - list of all commands\n'
             '/website - Samari.finance\n'
             '/chart - Poocoin chart\n'
             '/price - current price on PancakeSwap\n'
             '/marketcap or /mc - current marketcap of $SAMA\n'
             '\nShilling:\n'
             '/shillist - list of places to shill\n'
             '/shill or /shillin - templates for shilling on different platforms\n'
             '/shillreddit - template for reddit shill\n'
             '/shilltelegram or /shilltg - template for shill on Telegram\n'
             '/shilltwitter - template for twitter shill\n',
    "website": 'Samari.finance',
    "chart": '$SAMA is currently untracked.',  # todo
    "price": '$SAMA is currently untracked.',  # todo
    "mc": 'Market cap of $SAMA is untracked',  # todo
    "shillist":
        '\n@uniswaptalk'
        '\n@gemcollectors'
        '\n@cryptoM00NShots'
        '\n@gemdiscussion'
        '\n@gemtalkc'
        '\n@rocketmangem'
        '\n@dexgemschat'
        '\n@moonhunters'
        '\n@uniswapresearch'
        '\n@infinitygainzz'
        '\n@InfinityBotz'
        '\n@tehMoonwalkeRs'
        '\n@uniswaplegit -'
        '\n@uniswapgemtargets -'
        '\n@acmecrypto -'
        '\n@cryptomindsgroup -'
        '\n@oddgemsfamilia -'
        '\n@thegemhunterstg -'
        '\n@GoodFellas_Cryptopicks -'
        '\n@BitSquad -'
        '\n@themoonboyschat -'
        '\n@Farmingroom -'
        '\n@uniswapgemspumpz'
        '\n@Pumpchads'
        '\n@BitSquad'
        '\n@WhalersClub101'
        '\n@uniswapresearch'
        '\n@Uniswapelite'
        '\n@uniswapone'
        '\n@Uniswapchina'
        '\n@UniswapOTCexchange'
        '\n@shitcoincz'
        '\n@gemcollectors'
        '\n@Satoshi_club'
        '\n@gemcollectors'
        '\n@shitcoincz'
        '\n@CryptoVIPSignalTA'
        '\n@uniswap_gem_alerts'
        '\n@mrsjenny'
        '\n@binancedextrading'
        '\n@Cryptosupportservices'
        '\n@uniswapgem123'
        '\n@DeFiRaccoons'
        '\n@uniswapunofficial'
        '\n@CryptoFamilyGroup'
        '\n@CryproPriceTalks'
        '\n@UniswapEarlyCalls'
        '\n@elliotradescrypto'
        '\n@TradeCoinUnderGround'
        '\n@uniswapgemsv2'
        '\n@DevoToken'
        '\n@gemsfordegensgroup'
        '\n@uniswaptalk'
        '\n@crypto_revolution1'
        '\n\nHere is your shill list'
        '\n@BitSquad'
        '\n@WhalersClub101'
        '\n@uniswapresearch'
        '\n@Uniswapelite'
        '\n@uniswapone'
        '\n@Uniswapchina'
        '\n@UniswapOTCexchange'
        '\n@shitcoincz'
        '\n@gemcollectors'
        '\n@Satoshi_club'
        '\n@gemcollectors'
        '\n@shitcoincz'
        '\n@CryptoVIPSignalTA'
        '\n@uniswap_gem_alerts'
        '\n@binancedextrading'
        '\n@Cryptosupportservices'
        '\n@uniswapgem123'
        '\n@DeFiRaccoons'
        '\n@uniswapunofficial'
        '\n@CryptoFamilyGroup'
        '\n@cryptopricetalks'
        '\n@UniswapEarlyCalls'
        '\n@elliotradescrypto'
        '\n@TradeCoinUnderGround'
        '\n\nHere\'s the complete list of Telegram channels for shilling:'
        '\n@illuminatiGem'
        '\n@overdose_gems_group'
        '\n@SuicidalPumpGroup'
        '\n@elliotradescrypto'
        '\n@dexgemschat'
        '\n@GemSnipers'
        '\n@uniswapgemspumpz'
        '\n@defisearch'
        '\n@InfinityGainzz'
        '\n@gemcollectors'
        '\n@cryptodakurobinhooders'
        '\n@moonhunters'
        '\n@unigemchatz'
        '\n@supergemhunter'
        '\n@themoonboyschat'
        '\n@UniswapGemGroup'
        '\n@Uniswap_Gem_Dicuss'
        '\n@jumpsquad'
        '\n@BitSquad'
        '\n@WhalersClub101'
        '\n@uniswapresearch'
        '\n@Uniswapelite'
        '\n@uniswapone'
        '\n@Uniswapchina'
        '\n@UniswapOTCexchange'
        '\n@shitcoincz'
        '\n@Satoshi_club'
        '\n@CryptoVIPSignalTA'
        '\n@uniswap_gem_alerts'
        '\n@mrsjenny'
        '\n@binancedextrading'
        '\n@Cryptosupportservices'
        '\n@uniswapgem123'
        '\n@DeFiRaccoons'
        '\n@uniswapunofficial'
        '\n@CryptoFamilyGroup'
        '\n@CryproPriceTalks'
        '\n@UniswapEarlyCalls'
        '\n@TradeCoinUnderGround'
        '\n@uniswapgemsv2'
        '\n@defigemchat'
        '\n@sgdefi'
        '\n@The_Trading_Pit'
        '\n@uniswapgemtargets'
        '\n@de_fi'
        '\n@deficrew',
    "shillin": 'Available versions of shill are available:\n'
               '/shillreddit\n'
               '/shilltelegram or /shilltg\n'
               '/shilltwitter',
    "shillreddit": 'Implemented after website is launched',  # todo
    "shilltelegram": 'Implemented after website is launched',  # todo
    "shilltwitter": 'Implemented after website is launched',  # todo
}
